In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
b = np.array([3,2,1])

In [5]:
dot = 0
for e, f in zip(a,b):
    dot += e*f

In [6]:
dot

np.int64(10)

In [13]:
a@b


np.int64(10)

In [9]:
amag = np.sqrt(a@a)

In [10]:
bmag = np.sqrt(b@b)

In [12]:
cos = (a@b)/(bmag*amag)
cos

np.float64(0.7142857142857143)

In [3]:
A = np.array([[1,2],[3,4]])

In [4]:
A

array([[1, 2],
       [3, 4]])

In [5]:
A.T

array([[1, 3],
       [2, 4]])

In [7]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [9]:
np.linalg.det(np.linalg.inv(A))

np.float64(-0.49999999999999967)

In [8]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])