# Example

In pure Python, loops and lists process data elements sequentially, creating massive overhead for big data arrays. NumPy replaces this with the ndarray (N-dimensional array). It enforces a single data type (dtype) per array, allowing calculations to execute in compiled C memory space. This shifts your approach from element-by-element loops to block-level array thinking.

In [4]:
import numpy as np

# Convert a standard Python list into a continuous-memory NumPy block
python_list = [10, 20, 30]
arr = np.array(python_list, dtype=np.float32)

In [5]:
# Checking structural attributes of our vector data
print(f"Data type: {arr.dtype}")  # Output: float32
print(f"Dimensions: {arr.ndim}")  # Output: 1 (It's a rank-1 tensor / vector)
print(f"Shape: {arr.shape}")      # Output: (3,) -> 3 elements along 1 axis

Data type: float32
Dimensions: 1
Shape: (3,)


In [6]:
# Vectorized operation: Scalar addition applied to the entire block at once
shifted_arr = arr + 5.0
print(shifted_arr)                 # Output: [15.  25.  35.]

[15. 25. 35.]


# Exercise

Create a 1D NumPy array containing the values [1, 2, 3, 4, 5] but explicitly force its data type to be a 64-bit float during creation. Print the array's shape and its dtype to verify.

In [7]:
list = [1, 2, 3, 4, 5]
arr = np.array(list, dtype=np.float64)

print(f"Array's Shape: {arr.shape}")
print(f"Array's dtype: {arr.dtype}")

Array's Shape: (5,)
Array's dtype: float64


# Example

Every matrix or tensor has a structural geometry defined by its shape attribute. In AI models, layers change data dimensions dynamically (e.g., changing text sequence batches into feature embedding arrays). The .reshape() method modifies this geometric configuration without copying or altering the underlying data in memory.

In [8]:
import numpy as np

# Create a flat 1D vector containing 6 elements
flat_vector = np.array([1, 2, 3, 4, 5, 6])
print(f"Original: {flat_vector} | Shape: {flat_vector.shape}") 

# Reshape into a 2D matrix (2 rows, 3 columns)
matrix_2d = flat_vector.reshape(2,3)
print(matrix_2d)

Original: [1 2 3 4 5 6] | Shape: (6,)
[[1 2 3]
 [4 5 6]]


In [9]:
# Special trick: Pass -1 to let NumPy automatically calculate that dimension
auto_matrix = flat_vector.reshape(3, -1)
print(auto_matrix.shape) # Output: (3, 2) -> Calculated 6 elements / 3 rows = 2 cols

(3, 2)


# Exercise

Create a flat 1D array with values from 1 to 8 inclusive. Reshape it into a 3D tensor with a shape of (2, 2, 2). Print the resulting tensor.

In [10]:
flat_vector_exe = np.array([1, 2, 3, 4, 5, 6, 7, 8])
matrix_3d_exe = flat_vector_exe.reshape(2, 2, -1) 

print(matrix_3d_exe)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Example

Extracting specific slices of spatial data (like cropping regions in computer vision or extracting token segments in NLP) requires array slicing. For multi-dimensional matrices, slicing uses the format array[row_start:row_end, col_start:col_end]. Omitting the index integers entirely via a bare colon : signals NumPy to select the entire axis.

In [11]:
import numpy as np

# Create a 3x3 matrix representing mock feature states
matrix = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Example A: Extracting a localized 2x2 subarray patch from the top-left
# Rows 0 up to 2 (0, 1), Columns 0 up to 2 (0, 1)
patch = matrix[0:2, 0:2]
print(patch)

# Example B: Extracting all rows, but isolating ONLY the second column (index 1)
col_vector = matrix[:, 1]
print(col_vector) # Output: [11 14 17]

[[10 11]
 [13 14]]
[11 14 17]


# Exercise

Given the following 4x4 coordinate matrix:
grid = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

Write a slice statement to extract the inner 2x2 square containing the values [[6, 7], [10, 11]]. Print the result.

In [12]:
grid = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

patch_exe = grid[1:3, 1:3]
print(patch_exe)

[[ 6  7]
 [10 11]]


# Example

Broadcasting allows element-wise mathematical operations between arrays of different shapes. Instead of copying data to match sizes, NumPy virtually expands the smaller array across the larger one's missing dimensions. This operation relies on a strict rule: two dimensions are compatible if they are equal, or if one of them is exactly 1.

In [13]:
import numpy as np

# A 3x2 matrix (e.g., a batch of 3 samples, each with 2 features)
matrix = np.array([[1.0, 2.0], 
                   [3.0, 4.0], 
                   [5.0, 6.0]])

# A 1x2 row vector (e.g., feature-wise bias values)
bias = np.array([10.0, 20.0])

In [14]:
# Broadcasting occurs: bias virtually stretches vertically to shape (3, 2)
# Row 0 gets +10 to first element, +20 to second element, and so on.
result = matrix + bias

print(result)

[[11. 22.]
 [13. 24.]
 [15. 26.]]


# Exercise

You have a 3x3 weight matrix and a column vector of scale factors:
weights = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
scale = np.array([[10], [20], [30]]) # Shape: (3, 1)

Multiply weights by scale using broadcasting so that every element in row 0 is multiplied by 10, every element in row 1 by 20, and every element in row 2 by 30. Print the result.

In [15]:
weights = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
scale = np.array([[10], [20], [30]]) # Shape: (3, 1)

matmul = weights*scale
print(matmul)

[[ 10  20  30]
 [ 80 100 120]
 [210 240 270]]


# Example

Data preparation pipelines heavily rely on statistical aggregations like np.min(), np.max(), and np.mean(). In multi-dimensional arrays, you must specify the processing direction using the axis parameter.

    axis=0 compresses the array downward across rows (evaluating columns).

    axis=1 compresses the array sideways across columns (evaluating rows).

In [16]:
import numpy as np

matrix = np.array([[10, 2,  3],
                   [4,  5,  60]])

# Global maximum across the whole block
print(np.max(matrix))  # Output: 60

# Column-wise minimums (checks downward: min of [10,4], min of [2,5], min of [3,60])
print(np.min(matrix, axis=0))  # Output: [4 2 3]

# Row-wise means (checks across: mean of row 0, mean of row 1)
print(np.mean(matrix, axis=1))  # Output: [5. 23.]

60
[4 2 3]
[ 5. 23.]


# Exercise

Given the following experimental feature array:
features = np.array([
    [12, 15, 18],
    [20, 22, 26],
    [14, 19, 21]
])

Calculate and print the maximum value found within each row (sideways compression).

In [19]:
features = np.array([
    [12, 15, 18],
    [20, 22, 26],
    [14, 19, 21]
])

print(np.max(features, axis=1)) 

[18 26 21]


# FINAL EXERCISE

Objective:
Build a row-normalization processing function. In deep learning pipelines (like preparing input embeddings or processing pixel feature states), normalizing inputs across a specific axis ensures that features stay bounded, accelerating network convergence.

Requirements:
1. Create a 2D NumPy array with a shape of (4, 3) populated with random floating-point values.
2. For each independent row in that matrix, normalize the values using Min-Max scaling. The math formula to scale a target value x to a range between 0 and 1 is:
    xscaled=(x - min)/ (max - min)    where min and max are the minimum and maximum values of that specific row.
3. Your final output matrix must retain the original (4, 3) structural shape.
4. Print the final normalized matrix.
5. Programmatically verify that the minimum value of every single row is exactly 0.0 and the maximum value of every single row is exactly 1.0.

In [23]:
matrix = np.random.rand(4, 3)

row_min = matrix.min(axis=1, keepdims=True)
row_max = matrix.max(axis=1, keepdims=True)

normalized_matrix = (matrix - row_min) / (row_max - row_min)

# Print the normalized matrix
print("Normalized Matrix:")
print(normalized_matrix)

# Verify each row has min = 0.0 and max = 1.0
row_mins = normalized_matrix.min(axis=1)
row_maxs = normalized_matrix.max(axis=1)

print("\nRow-wise minimums:", row_mins)
print("Row-wise maximums:", row_maxs)

assert np.allclose(row_mins, 0.0), "At least one row does not have a minimum of 0.0"
assert np.allclose(row_maxs, 1.0), "At least one row does not have a maximum of 1.0"

print("\nVerification passed: Every row has min = 0.0 and max = 1.0")

Normalized Matrix:
[[1.         0.20949355 0.        ]
 [1.         0.15973638 0.        ]
 [0.         1.         0.97778582]
 [1.         0.         0.42643309]]

Row-wise minimums: [0. 0. 0. 0.]
Row-wise maximums: [1. 1. 1. 1.]

Verification passed: Every row has min = 0.0 and max = 1.0
