In [1]:
import torch

# 1. Create a tensor.
Think of this as defining an initial input variable.

We set requires_grad=True to tell PyTorch, "Track every mathematical operation I do to 'x'."

In [4]:
x = torch.tensor([2.0], requires_grad=True)

# 2. Perform an operation.
 Mathematically: y = x^2 + 3x

In [9]:
y = x**2 + 3*x

# 3. Calculate the gradients automatically.
This traverses the graph backwards. In calculus terms, it computes dy/dx.

In [10]:
y.backward()

# 4. Check the result.
The analytical derivative of x^2 + 3x is 2x + 3 and at x = 2.0, this is 2(2) + 3 = 7.

Let's see what Autograd calculated and stored inside x.grad:

In [11]:
print(x.grad)

tensor([7.])


In [12]:
x.data

tensor([2.])

In [14]:
x.detach()

tensor([2.])

# Exercise 1.1

In [28]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)

c=a**3 + b**2

d=4*c
d.backward()

print(a.grad)
print(b.grad)

tensor(48.)
tensor(24.)
